% -------------------------------------------------------------------
%  Generated by MATLAB on 19-Feb-2022 14:10:22
%  MATLAB version: 9.10.0.1851785 (R2021a) Update 6
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

cameraParams = saveVarsMat.cameraParams; % <1x1 cameraParameters> unsupported class

clear saveVarsMat;
